# Welcome to my Tutorial for Artificial Neural Network
# Artificial Neural Network

# Getting more underestanding about our dataset:
* This is a dataset for a bank which collects information about the customers
* RowNumber: is an irrelevent feature that we are going to get rid of it in the future 
* Customerid: is the identification key of each customer
* Surname: is the surname of each customer
* CreditScore: is the credit score of each customer
* Geography: means the conutry which each customer lives in
* Gender: is the gender of each customer
* Age: is the age of each customer
* Tenure:means the number of the year(s) which customer in the bank
* Balance: means the amount of money that each customer has in their account
* NumOfProducts: the number of the product(s) which customer uses like Credict card, Master Card Etc,
* HasCrCard: means if the customer has the credit card, 1 means Yes and 0 means No
* isActiveMemebr: means if the customer is active or not which 1 means is a active customer
* EstimatedSalary: means the estimated salary of each customer
# Target
* Exited: means if the customer exists the bank or not, 1 means the customer left the bank 

# First, we are going to import the libraries


In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.3.1'

Great! we have tensorflow 2 and this works much better than tensorflow 1 

# Let's import the dataset into the kernel

## Part 1 - Data Preprocessing

In [3]:
dataset = pd.read_csv('../input/churn-predictions-personal/Churn_Predictions.csv')
X = dataset.iloc[:, 3:-1].values #we select all th features except RowNumber, Customerid, Surname, Exited
y = dataset.iloc[:, -1].values #we select the target feature Exited for the y

In [4]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

# Label Encoding the "Gender" column

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


Great, we encoded the Gender feature, we have 0 code for Female category

* One Hot Encoding the "Geography" column

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Great, we encoded the Geography Column

### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling
* Notice: This is a very important and fundamental step for implementing the Deep Learning 

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [13]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 987us/step - loss: 0.5302 - accuracy: 0.7874
Epoch 2/100
250/250 [==============================] - 0s 987us/step - loss: 0.4687 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4497 - accuracy: 0.7966
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4385 - accuracy: 0.8033
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4310 - accuracy: 0.8089
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4256 - accuracy: 0.8134
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4204 - accuracy: 0.8135
Epoch 8/100
250/250 [==============================] - 0s 993us/step - loss: 0.4159 - accuracy: 0.8163
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4115 - accuracy: 0.8167
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4073 - 

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

In [19]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [20]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1517   78]
 [ 195  210]]


0.8635